# This is a basic workflow to help you get started with Actions
# https://zzsza.github.io/development/2020/06/06/github-action/
# https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: Naver RE Crawler

on:
  schedule:
    - cron: '0 5 * * *' # runs at 05:00 UTC everyday (14:00 Seoul)
    # https://crontab.guru/#0_5_*_*_*
  
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner
          
    - name: Set up Python 3.7
      uses: actions/setup-python@v2 
      with:
        python-version: 3.7 # install the python version needed
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    
    - name: Execute python script
      #env:
      #  ENV_A: ${{ secrets.ENV_A }}
      run: python crawler.py
      working-directory: ./crawler
    - name: Commit result files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"
        git add -A
        git commit -m "update data" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        branch: main
      
